### ISSUE TITLE
TestElementEntities should drop items with defining nbt

### ISSUE THREAD

**Issue by phantomeye1931** [snowy-shack/PortalMod#40]
If you pick up a turret or cube, it should maybe keep aspects like the customName, infiniteAmmo tags etc

**Comment by phantomeye1931** [comment]
@LarsMans64 thoughts?

**Comment by LarsMans64** [comment]
yes

**Comment by LarsMans64** [comment]
although infiniteAmmo shouldnt get saved. what tags besides customname should the item get too?
